Fix/from dict del pk key
PnX-SI/Utils-Flask-SQLAlchemy pull request #29
Opened 2022-11-18 15:55 UTC by joelclems

2022-11-20 13:00 UTC, bouttier requested changes

2022-11-20 13:00 UTC, bouttier commented on docs/changelog.rst
> +  * ajout d'un test sur l'existance d'une valeur de clé primaire nulle dans les données avec de la supprimer.
```suggestion
  * ajout d'un test sur l’existence d'une valeur de clé primaire nulle dans les données avant de la supprimer.
```

2022-11-20 13:00 UTC, bouttier commented on src/utils_flask_sqla/serializers.py
> +                    if id_field_name in data and id_value is None:
Block if à supprimer, simplement remplacer
```
id_value = data.get(id_field_name)
```
par
```
id_value = data.pop(id_field_name, None)
```

2022-11-22 08:17 UTC, joelclems commented on src/utils_flask_sqla/serializers.py
> +                    if id_field_name in data and id_value is None:
Le but ici est d'éviter d'avoir un dicitonnaire avec une valeur null pour la clé primaire et dans ce cas on supprime la clé

s'il y a une valeur pour la clé on la garde

2023-06-06 07:32 UTC, TheoLechemia approved these changes

2023-06-06 07:44 UTC, merged